/** Localized search names from LibreOffice Core's fixed font-name dictionary. */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
// Source: https://github.com/LibreOffice/core/blob/bce0998afefdbc355585ca324285661a2170ba77/unotools/source/misc/fontdefs.cxx
// GetEnglishSearchFontName::aDictionary has 155 source entries and 153 distinct keys.
// Duplicate source keys retain their first entry.
export const LOCALIZED_FONT_SEARCH_NAMES = new Map([
  ['바탕', 'batang'],
  ['바탕체', 'batangche'],
  ['궁서', 'gungshu'],
  ['궁서체', 'gungshuche'],
  ['굴림', 'gulim'],
  ['굴림체', 'gulimche'],
  ['돋움', 'dotum'],
  ['돋움체', 'dotumche'],
  ['宋体', 'simsun'],
  ['新宋体', 'nsimsun'],
  ['黑体', 'simhei'],
  ['楷体', 'simkai'],
  ['中易宋体', 'zycjksun'],
  ['中易黑体', 'zycjkhei'],
  ['中易楷体', 'zycjkkai'],
  ['方正黑体', 'fzhei'],
  ['方正楷体', 'fzkai'],
  ['方正宋一', 'fzsong'],
  ['方正书宋', 'fzshusong'],
  ['方正仿宋', 'fzfangsong'],
  ['m简黑', 'mhei'],
  ['m潠窪', 'mhei'],
  ['m简楷噬', 'mkai'],
  ['m潠翱抎', 'mkai'],
  ['m简宋', 'msong'],
  ['m潠冼', 'msong'],
  ['m简夫宋', 'cfangsong'],
  ['m潠溘冼', 'cfangsong'],
  ['細明體', 'mingliu'],
  ['新細明體', 'pmingliu'],
  ['桥', 'hei'],
  ['歡', 'kai'],
  ['浩湧', 'ming'],
  ['msゴシック', 'msgothic'],
  ['mspゴシック', 'mspgothic'],
  ['ms明朝', 'msmincho'],
  ['msp明朝', 'mspmincho'],
  ['微軟正黑體', 'microsoftjhenghei'],
  ['微软雅黑', 'microsoftyahei'],
  ['メイリオ', 'meiryo'],
  ['hg明朝l', 'hgminchol'],
  ['hgゴシックb', 'hggothicb'],
  ['hgp明朝l', 'hgpminchol'],
  ['hgpゴシックb', 'hgpgothicb'],
  ['hg明朝lsun', 'hgmincholsun'],
  ['hgゴシックbsun', 'hggothicbsun'],
  ['hgp明朝lsun', 'hgpmincholsun'],
  ['hgpゴシックbsun', 'hgpgothicbsun'],
  ['hg平成明朝体', 'hgheiseimin'],
  ['hg平成明朝体w3x12', 'hgheiseimin'],
  ['ipa明朝', 'ipamincho'],
  ['ipap明朝', 'ipapmincho'],
  ['ipaゴシック', 'ipagothic'],
  ['ipapゴシック', 'ipapgothic'],
  ['ipauiゴシック', 'ipauigothic'],
  ['takao明朝', 'takaomincho'],
  ['takaop明朝', 'takaopmincho'],
  ['takaoゴシック', 'takaogothic'],
  ['takaopゴシック', 'takaopgothic'],
  ['さざなみ明朝', 'sazanamimincho'],
  ['さざなみゴシック', 'sazanamigothic'],
  ['東風明朝', 'kochimincho'],
  ['東風ゴシック', 'kochigothic'],
  ['썬돋움', 'sundotum'],
  ['썬굴림', 'sungulim'],
  ['썬바탕', 'sunbatang'],
  ['백묵돋움', 'baekmukdotum'],
  ['백묵굴림', 'baekmukgulim'],
  ['백묵바탕', 'baekmukbatang'],
  ['方正黑體', 'fzheiti'],
  ['方正楷體', 'fzkaitib'],
  ['方正明體', 'fzmingtib'],
  ['方正宋体', 'fzsongti'],
  ['hy견명조', 'hymyeongjoextra'],
  ['hy신명조', 'hysinmyeongjomedium'],
  ['hy중고딕', 'hygothicmedium'],
  ['hy그래픽m', 'hygraphicmedium'],
  ['hy그래픽', 'hygraphic'],
  ['새굴림', 'newgulim'],
  ['썬궁서', 'sungungseo'],
  ['hy궁서b', 'hygungsobold'],
  ['hy궁서', 'hygungso'],
  ['썬헤드라인', 'sunheadline'],
  ['hy헤드라인m', 'hyheadlinemedium'],
  ['hy헤드라인', 'hyheadline'],
  ['휴먼옛체', 'yetr'],
  ['hy견고딕', 'hygothicextra'],
  ['썬목판', 'sunmokpan'],
  ['썬엽서', 'sunyeopseo'],
  ['썬백송', 'sunbaeksong'],
  ['hy엽서l', 'hypostlight'],
  ['hy엽서', 'hypost'],
  ['휴먼매직체', 'magicr'],
  ['썬크리스탈', 'suncrystal'],
  ['썬샘물', 'sunsaemmul'],
  ['hy얕은샘물m', 'hyshortsamulmedium'],
  ['hy얕은샘물', 'hyshortsamul'],
  ['한컴바탕', 'haansoftbatang'],
  ['한컴돋움', 'haansoftdotum'],
  ['한양해서', 'hyhaeseo'],
  ['md솔체', 'mdsol'],
  ['md개성체', 'mdgaesung'],
  ['md아트체', 'mdart'],
  ['md아롱체', 'mdalong'],
  ['md이솝체', 'mdeasop'],
  ['hgｺﾞｼｯｸe', 'hggothice'],
  ['hgpｺﾞｼｯｸe', 'hgpgothice'],
  ['hgsｺﾞｼｯｸe', 'hgsgothice'],
  ['hgｺﾞｼｯｸm', 'hggothicm'],
  ['hgpｺﾞｼｯｸm', 'hgpgothicm'],
  ['hgsｺﾞｼｯｸm', 'hgsgothicm'],
  ['hg行書体', 'hggyoshotai'],
  ['hgp行書体', 'hgpgyoshotai'],
  ['hgs行書体', 'hgsgyoshotai'],
  ['hg教科書体', 'hgkyokashotai'],
  ['hgp教科書体', 'hgpkyokashotai'],
  ['hgs教科書体', 'hgskyokashotai'],
  ['hg明朝b', 'hgminchob'],
  ['hgp明朝b', 'hgpminchob'],
  ['hgs明朝b', 'hgsminchob'],
  ['hg明朝e', 'hgminchoe'],
  ['hgp明朝e', 'hgpminchoe'],
  ['hgs明朝e', 'hgsminchoe'],
  ['hg創英角ﾎﾟｯﾌﾟ体', 'hgsoeikakupoptai'],
  ['hgp創英角ﾎﾟｯﾌﾟ体', 'hgpsoeikakupopta'],
  ['hgs創英角ﾎﾟｯﾌﾟ体', 'hgssoeikakupopta'],
  ['hg創英ﾌﾟﾚｾﾞﾝｽeb', 'hgsoeipresenceeb'],
  ['hgp創英ﾌﾟﾚｾﾞﾝｽeb', 'hgpsoeipresenceeb'],
  ['hgs創英ﾌﾟﾚｾﾞﾝｽeb', 'hgssoeipresenceeb'],
  ['hg創英角ｺﾞｼｯｸub', 'hgsoeikakugothicub'],
  ['hgp創英角ｺﾞｼｯｸub', 'hgpsoeikakugothicub'],
  ['hgs創英角ｺﾞｼｯｸub', 'hgssoeikakugothicub'],
  ['hg正楷書体-pro', 'hgseikaishotaipro'],
  ['hg丸ｺﾞｼｯｸ-pro', 'hgmarugothicmpro'],
  ['ヒラギノ明朝pro', 'hiraginominchopro'],
  ['ヒラギノ明朝pron', 'hiraginominchopron'],
  ['ヒラギノ角ゴシック', 'hiraginosans'],
  ['ヒラギノ角ゴpro', 'hiraginokakugothicpro'],
  ['ヒラギノ角ゴpron', 'hiraginokakugothicpron'],
  ['ヒラギノ丸ゴpro', 'hiraginomarugothicpro'],
  ['ヒラギノ丸ゴpron', 'hiraginomarugothicpron'],
  ['游ゴシック', 'yugothic'],
  ['游ゴシック体', 'yugothictai'],
  ['游明朝', 'yumincho'],
  ['游明朝体', 'yuminchotai'],
  ['源ノ角ゴシック', 'sourcehansans'],
  ['源ノ角ゴシックjp', 'sourcehansansjp'],
  ['源ノ角ゴシックhw', 'sourcehansanshw'],
  ['源ノ明朝', 'sourcehanserif'],
  ['源ノ明朝jp', 'sourcehanserifjp'],
  ['ipamj明朝', 'ipamjmincho'],
  ['ipaexゴシック', 'ipaexgothic'],
  ['ipaex明朝', 'ipaexmimcho'],
])
